name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: nightly}
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: 1.0.0}
          - {os: ubuntu-latest, crystal: 0.36.1}
          - {os: ubuntu-latest, crystal: 0.35.1}
          - {os: ubuntu-latest, crystal: 0.34.0}
    runs-on: ${{matrix.os}}
    steps:
      - run: apt-get install redis-server
      - run: sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
      - run: sudo mv redis.conf /etc/redis
      - run: sudo service redis-server start
      - run: echo PING | nc localhost 6379
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - uses: actions/checkout@v2
      - run: shards install --ignore-crystal-version
      - run: crystal spec
      - run: crystal tool format --check

